#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
V838 Mon Light Echo Pipeline (updated for actual project file layout)
--------------------------------------------------------------------
Reads CSV inputs from:
    data/derived/Echo of Light/input

Expected default files in that folder:
    - v838mon_measurements_verified.csv
    - v838mon_model_input_all.csv
    - v838mon_model_input_tylenda.csv
    - v838mon_model_input_crause.csv

Writes timestamped results under:
    results/Echo of Light/output/YYYYMMDD_HHMMSS

Recommended script location:
    src/echo of light/v838mon/v838mon_echo_pipeline_updated.py
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path

import pandas as pd


DEFAULT_INPUT_DIR = Path("data/derived/Echo of Light/input")
DEFAULT_RESULTS_ROOT = Path("results/Echo of Light/output")


def ensure_file(path: Path) -> Path:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return path


def load_csv(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, encoding="utf-8-sig")


def write_csv(df: pd.DataFrame, path: Path) -> None:
    df.to_csv(path, index=False, encoding="utf-8-sig")


def make_output_dir(root: Path) -> Path:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = root / ts
    out.mkdir(parents=True, exist_ok=True)
    return out


def build_summary(
    verified_df: pd.DataFrame,
    all_df: pd.DataFrame,
    tylenda_df: pd.DataFrame,
    crause_df: pd.DataFrame,
    out_dir: Path,
    input_dir: Path,
    filenames: dict,
) -> dict:
    return {
        "pipeline_name": "V838 Mon Light Echo Pipeline (updated)",
        "created_at": datetime.now().isoformat(),
        "input_dir": str(input_dir),
        "results_dir": str(out_dir),
        "input_files": filenames,
        "row_counts": {
            "measurements_verified": int(len(verified_df)),
            "model_input_all": int(len(all_df)),
            "model_input_tylenda": int(len(tylenda_df)),
            "model_input_crause": int(len(crause_df)),
        },
        "dataset_counts_in_verified": (
            verified_df["dataset"].astype(str).value_counts().to_dict()
            if "dataset" in verified_df.columns else {}
        ),
        "notes": [
            "This version matches the actual files currently listed in data/derived/Echo of Light/input.",
            "It does not expect V838Mon_sources.csv or V838Mon_epochs.csv in the input folder.",
            "It preserves verified and model-input tables as separate outputs.",
            "Tylenda and Crause time conventions remain intentionally separated.",
        ],
    }


def write_readme(out_dir: Path) -> None:
    text = """README_results.txt
==================

This results folder was generated by:
    src/echo of light/v838mon/v838mon_echo_pipeline_updated.py

Expected project input files
----------------------------
- v838mon_measurements_verified.csv
- v838mon_model_input_all.csv
- v838mon_model_input_tylenda.csv
- v838mon_model_input_crause.csv

Files written here
------------------
- verified_copy.csv
- model_input_all_copy.csv
- model_input_tylenda_copy.csv
- model_input_crause_copy.csv
- verified_tylenda_only.csv
- verified_crause_only.csv
- dataset_row_counts.csv
- summary.json
- README_results.txt

Meaning
-------
This pipeline version is aligned with the actual project folder listing and copies,
separates, and summarizes the already-prepared V838 Mon input tables.

Important caution
-----------------
Tylenda and Crause time systems are still different.
Do not merge or reinterpret them without explicit conversion.
"""
    (out_dir / "README_results.txt").write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Updated V838 Mon pipeline for actual project layout")
    parser.add_argument("--input-dir", default=str(DEFAULT_INPUT_DIR))
    parser.add_argument("--results-root", default=str(DEFAULT_RESULTS_ROOT))
    parser.add_argument("--verified-csv", default="v838mon_measurements_verified.csv")
    parser.add_argument("--all-csv", default="v838mon_model_input_all.csv")
    parser.add_argument("--tylenda-csv", default="v838mon_model_input_tylenda.csv")
    parser.add_argument("--crause-csv", default="v838mon_model_input_crause.csv")
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    results_root = Path(args.results_root)

    verified_path = ensure_file(input_dir / args.verified_csv)
    all_path = ensure_file(input_dir / args.all_csv)
    tylenda_path = ensure_file(input_dir / args.tylenda_csv)
    crause_path = ensure_file(input_dir / args.crause_csv)

    verified_df = load_csv(verified_path)
    all_df = load_csv(all_path)
    tylenda_df = load_csv(tylenda_path)
    crause_df = load_csv(crause_path)

    out_dir = make_output_dir(results_root)

    write_csv(verified_df, out_dir / "verified_copy.csv")
    write_csv(all_df, out_dir / "model_input_all_copy.csv")
    write_csv(tylenda_df, out_dir / "model_input_tylenda_copy.csv")
    write_csv(crause_df, out_dir / "model_input_crause_copy.csv")

    if "dataset" in verified_df.columns:
        verified_tylenda = verified_df[verified_df["dataset"].astype(str).str.startswith("Tylenda", na=False)].copy()
        verified_crause = verified_df[verified_df["dataset"].astype(str).str.startswith("Crause", na=False)].copy()
    else:
        verified_tylenda = pd.DataFrame()
        verified_crause = pd.DataFrame()

    write_csv(verified_tylenda, out_dir / "verified_tylenda_only.csv")
    write_csv(verified_crause, out_dir / "verified_crause_only.csv")

    counts_df = pd.DataFrame(
        [
            {"file": "verified", "rows": len(verified_df)},
            {"file": "model_input_all", "rows": len(all_df)},
            {"file": "model_input_tylenda", "rows": len(tylenda_df)},
            {"file": "model_input_crause", "rows": len(crause_df)},
            {"file": "verified_tylenda_only", "rows": len(verified_tylenda)},
            {"file": "verified_crause_only", "rows": len(verified_crause)},
        ]
    )
    write_csv(counts_df, out_dir / "dataset_row_counts.csv")

    summary = build_summary(
        verified_df,
        all_df,
        tylenda_df,
        crause_df,
        out_dir,
        input_dir,
        {
            "verified_csv": args.verified_csv,
            "all_csv": args.all_csv,
            "tylenda_csv": args.tylenda_csv,
            "crause_csv": args.crause_csv,
        },
    )
    with (out_dir / "summary.json").open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    write_readme(out_dir)
    print(f"[DONE] Results written to: {out_dir}")


if __name__ == "__main__":
    main()
